name: Build & Upload Artifact

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # 3. 构建项目
      - name: Build with Maven
        run: mvn clean package --batch-mode

      # 4. 上传构建产物到 GitHub Actions Artifact
      - name: Upload plugin JAR
        uses: actions/upload-artifact@v2
        with:
          name: SessionKickModifier
          path: target/SessionKickModifier-*.jar

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      # 下载刚才构建的 artifact
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: SessionKickModifier

      # 在 Release 页面自动附加 JAR（如果你想在打 Tag 时自动发布）
      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v1
        with:
          files: SessionKickModifier-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
